name: Button Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: chabad360/html-proofer@master
        with:
            directory: ./


      - name: Validate CSS
        run: npx stylelint "**/*.css"
